[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
LogLinearSDDP = "e4ebbe64-fbf7-4134-b817-90c0e2e18f7d"
SDDP = "f4570300-c277-11e8-125c-4912f86ce65d"
